name: 'version-test-dummy'
description: 'Dummy function for testing ajparsons/sha-version-warning'
version: 0.1.0


outputs:
  warning_given:
    description: "If sha-version-warning gave a warning"
    value: ${{ steps.warning_step.outputs.warning_given }}

runs:
  using: "composite"
  steps:

      # call main because that's actually what we're testing here
    - name: Test if this action is being referenced safely
      id: warning_step
      uses: ajparsons/sha-version-warning@main
      with: 
        action_path: ${{ github.action_path }}
