name: '{{cookiecutter.lib_name}}'
description: '{{cookiecutter.description}}'
version: 0.1.0

inputs:
  example_input: 
    description: 'Example input'
    required: true
outputs:
  example_output:
    description: "The repo of 'user/repo'."
    value: ${{ '{{' }} steps.example_step.outputs.repo_name {{ '}}' }}

runs:
  using: "composite"
  steps:

    - name: Test if this action is being referenced safely
      uses: ajparsons/sha-version-warning@53c5e9cbf96afb276cb2cf486ebd45c5d5db0e11 # v1.0.1
      with: 
        action_path: ${{ '{{' }} github.action_path {{ '}}' }}

    - name: Example step
      id: example_step
      shell: bash
      run: |
        echo "example_output=hello world $EXAMPLE_INPUT" >> $GITHUB_OUTPUT
      env:
        EXAMPLE_INPUT: ${{ '{{' }} inputs.example_input {{ '}}' }}
    
